// <auto-generated />
namespace TransactionTask.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NotNullableUserFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotNullableUserFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311021059_NotNullableUserFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
